name: publish kormoc/pigen:$TAG

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Set up buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build
        run: docker buildx build --memory="1536m" --push --tag kormoc/pigen:$TAG --platform linux/amd64,linux/arm64,linux/arm/v7 .
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}
