name: publish kormoc/pigen:tag

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: docker buildx build --tag kormoc/pigen:$TAG --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}
